FROM quay.io/keycloak/keycloak:25.0.0 as builder

# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

WORKDIR /opt/keycloak
# for demonstration purposes only, please make sure to use proper certificates in production instead
RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:25.0.0
COPY --from=builder /opt/keycloak/ /opt/keycloak/

# change these values to point to a running postgres instance
ENV KC_DB=postgres
#ENV KC_DB_URL=jdbc:postgresql://localhost:5432/postgres-db
ENV KC_DB_URL=jdbc:postgresql://ep-white-paper-a5tokfkt.us-east-2.aws.neon.tech/keyauth
#ENV KC_DB_USERNAME=
#ENV KC_DB_PASSWORD=
ENV KC_DB_URL_HOST=ep-white-paper-a5tokfkt.us-east-2.aws.neon.tech

#ENV KEYCLOAK_ADMIN=
#ENV KEYCLOAK_ADMIN_PASSWORD=
ENV KC_HOSTNAME_STRICT=false
ENV KC_HOSTNAME_STRICT_HTTPS=false
ENV KC_HTTP_ENABLED=true 
ENV KC_PROXY=edge
ENV KC_HOSTNAME=localhost
ENV KC_HOSTNAME_PORT=8080

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]